SET DEFINE OFF;
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2522, 'SAMSUN', 'İL SANTRALLER MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10003, 'ISPARTA', 'OPERASYON MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10057, 'MANİSA', 'HUKUK İŞLERİ MÜD.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8061, 'MANİSA', 'BİLGİ İŞLEM MUD');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4982, 'MANİSA', 'MANİSA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4756, 'UŞAK', 'MUHASEBE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3504, 'DİYARBAKIR', 'BİSMİL İŞLETME ŞEFLİĞİ55');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3563, 'İSTANBUL AVR.', 'GELİRLER TAKİP MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3988, 'İSTANBUL AVR.', 'FİBER OPTİK KABLO MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10208, 'İSTANBUL AVR.', 'HUKUK İŞLERİ MÜD');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6547, 'İSTANBUL AVR.', 'MUHASEBE MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9376, 'İSTANBUL AVR.', 'KURUMSAL SATIŞ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10526, 'İSTANBUL(AVRUPA)', 'TOPTAN SATIŞ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9787, 'İSTANBUL(AVRUPA)', 'KURUMSAK GÜVENLİK HİZMETLERİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5024, 'ESKİŞEHİR', 'BİLGİ İŞLEM MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4755, 'ESKİŞEHİR', 'KAMBS');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9147, 'BURSA', 'BAYİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4526, 'BURSA', 'KURUMSAL SATIŞ MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10185, 'İZMİR', 'ERİŞİM OPERASYON');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7334, 'İZMİR', 'İZMİR TRANSMİSYON');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10514, 'ERZURUM', 'BİLGİ İŞLEM MÜD.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10179, 'ERZURUM', 'MAK.ENJ.SOĞ.SİS.MÜD');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7134, 'ERZURUM', 'İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3902, 'EDİRNE', 'FİNANS&TEDARİK ZİNCİRİ UZM.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8574, 'EDİRNE', 'HUKUK UZMANLIĞI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4121, 'EDİRNE', 'İL YÖNETİCİLERİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7474, 'KIRKLARELİ', 'BİLGİ İŞLEM');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9851, 'HAKKARİ', 'MUHASEBE MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6109, 'ANKARA', 'HUKUK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (11450, 'MERSİN (İÇEL)', 'HUKUK İŞLERİ MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8115, 'SİVAS', 'BİLGİ İŞLEM');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10232, 'SİVAS', 'SİVAS');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (12469, 'TOKAT', 'TOKAT İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8831, 'TOKAT', 'MUHASEBE MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (12014, 'ORDU', 'HUKUK UZMANLIĞI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (11740, 'SAMSUN', 'HUKUK MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4870, 'ZONGULDAK', 'FİNANS TEDARİK ZİNCİRİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10851, 'KIRKLARELİ', 'HUKUK MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6742, 'KIRKLARELİ', 'FİNANS VE TEDARİK ZİNCİRİ UZMA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9013, 'KONYA', 'MİM MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9060, 'KONYA', 'MUHASEBE MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (13009, 'MALATYA', 'BİLGİ İŞLEM MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10042, 'ORDU', 'MUHASEBE MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10059, 'GİRESUN', 'FİNANS&TEDARİK ZİNCİRİ UZMANLI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9063, 'GİRESUN', 'HUKUK İŞLERİ UZMANLIĞI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (11308, 'TRABZON', 'HUKUK MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9941, 'MUĞLA', 'İL_SANTRALLER_MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9578, 'MUĞLA', 'İL_ERİŞİM ŞEBEKELERİ MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6592, 'MUĞLA', 'İL_TRANSMİSYON_MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7807, 'MUĞLA', 'MUHASEBE İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (11815, 'MUĞLA', 'MUĞLA İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7474, 'ARTVİN', 'ERISIM');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (10776, 'ARTVİN', 'ÇORUH-FTTX');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9684, 'TEKİRDAĞ', 'MUHASEBE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (15076, 'ANTALYA', 'GUNEY1 BOLGE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (14567, 'AFYON', 'OPERASYON MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (18501, 'KIBRIS', 'KIBRIS');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7034, 'ADANA', 'CEYHAN');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2449, 'ADANA', 'MAHFESIĞMAZ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3946, 'ADANA', 'SEYHAN');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4276, 'ADANA', 'YÜREĞİR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6736, 'SAKARYA', 'SAKARYA İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3449, 'ADIYAMAN', 'İL MÜDÜRLÜK MERKEZ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6709, 'AFYON', 'AFYONKARAHİSAR İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3758, 'AĞRI', 'AĞRI İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3060, 'AKSARAY', 'AKSARAY İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5145, 'AMASYA', 'MERZİFON');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1331, 'AMASYA', 'YEŞİLIRMAK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7897, 'ANKARA', 'BAHÇELİEVLER');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1659, 'ANKARA', 'DİKMEN');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1041, 'ANKARA', 'İNCESU');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5383, 'ANKARA', 'KEÇİÖREN');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3578, 'ANKARA', 'POLATLI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8863, 'ANKARA', 'SİNCAN');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1447, 'ANKARA', 'ULUS');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8022, 'ANKARA', 'YENİMAHALLE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2784, 'ANKARA', 'YENİŞEHİR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4115, 'ANTALYA', 'ALANYA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1108, 'ANTALYA', 'GÜLLÜK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1164, 'ANTALYA', 'KIZILTOPRAK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1146, 'ANTALYA', 'MANAVGAT');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9009, 'ARDAHAN', 'ARDAHAN İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8391, 'ARTVİN', 'ARTVİN');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3496, 'AYDIN', 'ÇARŞI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2410, 'AYDIN', 'KUŞADASI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6920, 'AYDIN', 'NAZİLLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7314, 'AYDIN', 'SÖKE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4811, 'BİLECİK', 'BİLECİK İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5239, 'BALIKESİR', 'ALTI EYLÜL MÜD.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8084, 'BALIKESİR', 'BANDIRMA MÜD.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9017, 'BALIKESİR', 'EDREMİT MÜD.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5137, 'BİNGÖL', 'BİNGÖL İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2392, 'DÜZCE', 'DÜZCE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6194, 'BURDUR', 'İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5379, 'BURSA', 'GençOsman');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6076, 'BURSA', 'İNEGÖL');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8789, 'BURSA', 'SETBAŞI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5367, 'BARTIN', 'BARTIN İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2927, 'BİTLİS', 'KALE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5367, 'BATMAN', 'BATMAN İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3199, 'BAYBURT', 'BAYBURT İL');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5095, 'ÇANKIRI', 'KARATEKİN MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8869, 'ÇANAKKALE', 'BİGA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3516, 'ÇANAKKALE', '18 MART ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7764, 'DENİZLİ', 'ERİŞİM YTR. VE OPERASYON MÜD.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3525, 'DİYARBAKIR', 'BAĞLAR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1250, 'DİYARBAKIR', 'SURİÇİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4863, 'ELAZIĞ', 'HARPUT');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8679, 'ERZİNCAN', 'ERZİNCAN İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7071, 'ERZURUM', 'DOĞU I BÖLGE MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1868, 'ESKİŞEHİR', 'İKİ EYLÜL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6469, 'ESKİŞEHİR', 'YUNUSEMRE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5712, 'GÜMÜŞHANE', 'GÜMÜŞHANE İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4680, 'GİRESUN', 'GİRESUN İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1787, 'GAZİANTEP', 'NİZİP');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2542, 'GAZİANTEP', 'ŞAHİNBEY');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8018, 'GAZİANTEP', 'ŞEHİT KAMİL');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2165, 'HAKKARİ', 'HAKKARİ İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5183, 'HATAY', 'İSKENDERUN');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5487, 'IĞDIR', 'IĞDIR İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1308, 'ISPARTA', 'YALVAÇ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4639, 'ISPARTA', 'HALIKENT');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6251, 'İSTANBUL AND', 'ERENKÖY');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1778, 'İSTANBUL AND', 'KADIKÖY');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8669, 'İSTANBUL AND', 'KÜÇÜKYALI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8666, 'İSTANBUL AND', 'PENDİK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5826, 'İSTANBUL AND', 'ÜMRANİYE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1960, 'İSTANBUL AND', 'ÜSKÜDAR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7161, 'İSTANBUL AVR.', 'AVCILAR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6324, 'İSTANBUL AVR.', 'BAĞCILAR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5212, 'İSTANBUL AVR.', 'BAHÇELİEVLER');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9041, 'İSTANBUL AVR.', 'BAKIRKÖY');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3669, 'İSTANBUL AVR.', 'BAYRAMPAŞA (ESENLER)');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1450, 'İSTANBUL AVR.', 'BEBEK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7159, 'İSTANBUL AVR.', 'BEYOĞLU');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6024, 'İSTANBUL AVR.', 'BÜYÜKÇEKMECE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2662, 'İSTANBUL AVR.', 'EMİNÖNÜ MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3237, 'İSTANBUL AVR.', 'FATİH');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3176, 'İSTANBUL AVR.', 'GAYRETTEPE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4488, 'İSTANBUL AVR.', 'GAZİOSMANPAŞA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3308, 'İSTANBUL AVR.', 'GÖRÜNTÜLÜ TELEFON');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8949, 'İZMİR', 'İZMİR BAHÇELİEVLER');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6482, 'İZMİR', 'İZMİR BERGAMA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1843, 'İZMİR', 'BORNOVA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6065, 'İZMİR', 'İZMİR SAHİL');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4742, 'İZMİR', 'İZMİR KARABAĞLAR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7728, 'İZMİR', 'İZMİR KARŞIYAKA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4387, 'İZMİR', 'İZMİR KONAK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7231, 'İZMİR', 'İZMİR ÖDEMİŞ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4960, 'İZMİR', 'İZMİR ÇEŞME (YARIMADA)');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1840, 'İZMİR', 'İZMİR YENİŞEHİR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3220, 'KOCAELİ', 'ALEMDAR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8990, 'KOCAELİ', 'GEBZE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8434, 'KOCAELİ', 'GÖLCÜK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5856, 'KARS', 'KARS İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8520, 'KİLİS', 'KİLİS');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6242, 'KAHRAMANMARAŞ', 'ELBİSTAN İŞLETME UZMANLIĞI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8703, 'KONYA', 'AKŞEHİR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1664, 'KONYA', 'BEYŞEHİR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6550, 'KONYA', 'CİHANBEYLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1504, 'KONYA', 'EREĞLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4878, 'KONYA', 'ILGIN(KAPANDI)');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3321, 'KONYA', 'MEVLANA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7493, 'KONYA', 'SELÇUKLU(KAPANDI)');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7999, 'KARABÜK', 'İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3464, 'KIRIKKALE', 'CUMHURİYET');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7343, 'KIRKLARELİ', 'KIRKLARELİ İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6885, 'KARAMAN', 'KARAMAN');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3931, 'KIRŞEHİR', 'KIRŞEHİR İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5999, 'KAYSERİ', 'AYDINLIKEVLER');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2293, 'KAYSERİ', 'ERCİYES MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2080, 'MUĞLA', 'BODRUM MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2630, 'MUĞLA', 'FETHİYE MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6293, 'MUĞLA', 'MUĞLA İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6335, 'MUĞLA', 'MARMARİS MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8342, 'MUĞLA', 'MİLAS MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4940, 'MALATYA', 'MALATYA İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5125, 'MANİSA', 'AKHİSAR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6858, 'MANİSA', 'MESİR MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4584, 'MANİSA', 'SALİHLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6623, 'MARDİN', 'DİYARBAKIRKAPI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4136, 'MERSİN (İÇEL)', 'MEZİTLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7107, 'MERSİN (İÇEL)', 'SİLİFKE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5713, 'MERSİN (İÇEL)', 'TARSUS ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2021, 'MUŞ', 'TEK. İŞL. VE YAT. MÜD.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8513, 'NİĞDE', 'YENİCE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5783, 'NEVŞEHİR', 'NEVŞEHİR İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6642, 'ORDU', 'FATSA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6812, 'ORDU', 'ÜNYE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6637, 'ORDU', 'ONDOKUZ EYLÜL');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8159, 'OSMANİYE', 'OSMANİYE İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3688, 'OSMANİYE', 'OSMANİYE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7000, 'RİZE', 'RİZE İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6753, 'SİİRT', 'SİİRT İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1744, 'SAMSUN', 'BAFRA TLK.İŞL.UZMANLIĞI');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7891, 'SAMSUN', 'İLKADIM');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8889, 'SAMSUN', 'CANİK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8128, 'SİNOP', 'BOYABAT');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3890, 'SİNOP', 'SİNOP İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7612, 'SİVAS', 'SİVAS İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4664, 'ŞIRNAK', 'ŞIRNAK İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5616, 'ŞANLIURFA', 'SİVEREK');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8245, 'ŞANLIURFA', 'YENİŞEHIR');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6524, 'TEKİRDAĞ', 'ÇORLU');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7066, 'TEKİRDAĞ', 'TEKİRDAĞ İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8263, 'TOKAT', 'TURHAL');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4304, 'TUNCELİ', 'TUNCELİ İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1909, 'TRABZON', 'KANUNİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6305, 'UŞAK', 'KURTULUŞ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6673, 'VAN', 'VAN İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3790, 'YALOVA', 'YALOVA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3762, 'YOZGAT', 'YOZGAT İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (7694, 'ZONGULDAK', 'ZONGULDAK İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3184, 'ZONGULDAK', 'KARADENİZ EREĞLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2446, 'BURSA', 'NİLÜFER');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4311, 'MERSİN (İÇEL)', 'TOROSLAR ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8022, 'İZMİR', 'ÇİĞLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5053, 'MERSİN (İÇEL)', 'ERDEMLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5727, 'TRABZON', 'AKÇAABAT');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6417, 'ANTALYA', 'KUMLUCA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1486, 'KIRKLARELİ', 'LÜLEBURGAZ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1845, 'BURSA', 'M.KEMALPAŞA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2426, 'İSTANBUL AVR.', 'İKİTELLİ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5332, 'KIRKLARELİ', 'İPTAL');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9136, 'ZONGULDAK', 'HUKUK UZM.');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6899, 'GAZİANTEP', 'BİLGİ İŞLEM MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (8572, 'MUĞLA', 'MUĞLA İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1768, 'ANKARA', 'BİLGİ İŞLEM');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (2136, 'ANKARA', 'GELİRLER TAKİP');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (4719, 'ANKARA', 'MUHASEBE');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3650, 'ANKARA', 'KAMU SATIŞ MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (6397, 'ANKARA', 'TOPTAN SATIŞ MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (9045, 'GAZİANTEP', 'HUKUK İŞLERİ MÜD');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3030, 'KIRŞEHİR', 'HATA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (3678, 'GAZİANTEP', 'MUHASEBE MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (1681, 'MANİSA', 'İL MÜDÜRLÜĞÜ');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5525, 'ANTALYA', 'ANTALYA');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5295, 'İSTANBUL(ANADOLU)', 'İSTANBUL ÇÖZÜM');
Insert into EGITIM.MUDURLUK
   (MUDURLUK_KODU, IL_ADI, MUDURLUK_ADI)
 Values
   (5055, 'ADANA', 'ERİŞİM MÜDÜRLÜĞÜ');
COMMIT;
